name: Minimal Android CI Workflow

on:
    push:
        branches:
            -   master
            
jobs:
    test:
        name: Run Unit Tests
        run-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v1
            -   name: Setup JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            -   name: Run Tests
                run: bash ./gradlew test --stacktrace
